["ときのそら"]
channel = "UCp6993wxpyDPHUpavwDFqgg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQO9Vyz7ysAwPSio5xvkw6n0xvlyDu7A9eawqIH3w=s88-c-k-c0x00ffffff-no-rj-mo"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79dHleIBmBtLP2TfcmFpIJjmH7fa8tfG1qTKg=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "c0809c3c3c191b67"
youtube_img_hash = "c0809c3c3c191b67"

[AZKi]
channel = "UC0TXe_LYZ4scaW2XMyi5_kw"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQQhnWKHLOLxjnXksGHHC8bnVS2UniL8Od6JTEPWQ=s88-c-k-c0x00ffffff-no-rj"
youtube_img_hash = "4443818f9dc9ebff"

["ロボ子さん"]
channel = "UCDqI2jOz0weumE8s7paEk6g"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLTVWKjrovP0tGtguup9TYZicykceA45olVmEr2kvQ=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79oElMmkIk3cuUa-CZY72QHuWT-P8ETYWvZLw=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "fd038181878fcff3"
youtube_img_hash = "fd038181878fcff3"

["さくらみこ"]
channel = "UC-hM6YJuNYVAmUWxeIr9FeA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQlZnbXr-RooUQezemDKu7alJrZcEMy8_5P07ILug=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/ytc/AKedOLQlZnbXr-RooUQezemDKu7alJrZcEMy8_5P07ILug=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "ffdf9088bc39091e"
youtube_img_hash = "ffdf9088bc39091e"

["白上フブキ"]
channel = "UCdn5BQ06XqgXoAxIhbqw5Rg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQmM8F8S-7GTcF5Lw7fBALF8FQC9yNKTb_nFHev2w=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7-oeSvjxgdwMoDyT1LMH8nyqkWJCZH8MAOjzg=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "fe7effcbfffb8181"
youtube_img_hash = "fe7effcbfffb8181"

["夏色まつり"]
channel = "UCQ0UDLQCjY0rmuxCDE38FGg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQCXDfJbZoEZ-gtUiF4nSaGU8-qiq--BSTd92Sw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7_MTJEH9Kn-cVznPJPBt4v0BOkmd5btoSdz6Q=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "6272787078381c1c"
youtube_img_hash = "6272787078381c1c"

["夜空メル"]
channel = "UCD8HOxPs4Xvsm8H0ZxXGiBw"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLS8pa1lDGBL7tieftDRgPjVsSexeMJ9YURgBTXDMg=s88-c-k-c0x00ffffff-no-rj"
youtube_img_hash = "70fcfc783b0f0f17"
holodule_url = "https://yt3.ggpht.com/a/AGF-l788-g4hDYP2xcs7CJzeEBfsZ48EMSjcJCZjBA=s88-c-k-c0xffffffff-no-rj-mo"

["赤井はあと"]
channel = "UC1CfXB_kRs3C-zaeTG3oGyg"
youtube_url = "https://yt3.ggpht.com/rNj6bichsOoUjA2N9iXWxInEt9Y2Fo5fhG4S8oR17ip8ouCu_7wmX3PnQxt6OP6Rd9OlYXYcmw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7-ULNK73gTCGtPrM6elTCL-ValOSptM0YTXkQ=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "f9c191113d9bc3c3"
youtube_img_hash = "bf7fff3e3f3b2000"

["アキ・ローゼンタール"]
channel = "UCFTLzh12_nrtzqBPsTCqenA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLT4XEPRFwXpb4gZ1qco_xCOt7ems7SrUsGOkmXX=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7-MKGs8oe830HpPIlyQ3pNAVqUgqiMdSg8TwQ=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "b9bd93939999c066"

["湊あくあ"]
channel = "UC1opHUrw8rvnsadT-iGp7Cg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLTU65vMUk-G7g-5RR2OTTAM57CMqQCaV_50675x9A=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79lFypl4LxY5kf60UpCL6gakgSGHtN-t8hq1g=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "c3836038f0fcff67"
youtube_img_hash = "c3836038f0fcff67"

["癒月ちょこ"]
channel = "UC1suqwovbL1kzsoaZgFZLKg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQn_VxZ1ApMgQahrkcTtSdSAr6Jpxi4eHQiMnIlsw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79rj4svlTtPimVkcxdUJS8VGt01u_mqZWZIbA=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "db9bc3cbcbc33e7c"
youtube_img_hash = "db9bc3cbcbc33e7c"

["百鬼あやめ"]
channel = "UC7fk0CB07ly8oSl0aqKkqFg"
youtube_url = "https://yt3.ggpht.com/XDGhKwPZcT16Ppg2gQmLHEIYRhw9sY4rqG0HWbeCH68LHkhlVQrrFgxd5hWUuMb2nLfDOhu6=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/XDGhKwPZcT16Ppg2gQmLHEIYRhw9sY4rqG0HWbeCH68LHkhlVQrrFgxd5hWUuMb2nLfDOhu6=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "70f8fffffc38c800"
youtube_img_hash = "70f8fffdfc38c800"

["紫咲シオン"]
channel = "UCXTpFs_3PqI41qX2d9tL2Rw"
youtube_url = "https://yt3.ggpht.com/AyUL9W0ltc_aJr_MysuZBx8hRfb1SIVNREgU9kiOO-lqmdhYkEsllmhagertVIwHwa3UAAKy=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/AyUL9W0ltc_aJr_MysuZBx8hRfb1SIVNREgU9kiOO-lqmdhYkEsllmhagertVIwHwa3UAAKy=s88-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "1e3fff9f3338104f"
youtube_img_hash = "1e3fff9f3338104f"

["大空スバル"]
channel = "UCvzGlP9oQwU--Y0r9id_jnA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLTf1BZdgOX5oC0SB-B_Uq16OlomzqRH81ADPPlPcA=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79ydxWz0XWeOkKy59UT9X_pPEMBzIO2-W0GTg=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "0040607c3e7e3cc9"
youtube_img_hash = "0040607c3e7e3cc9"

["大神ミオ"]
channel = "UCp-5t9SrOQwXMU7iIjQfARg"
youtube_url = "https://yt3.ggpht.com/Z78RNXxUqpOGYKFt-VrJV7nlehOHzl7Ta-l1cgPx5Ewucmr5kY64iGxmPSe7QqIdM1ZhvPlEOg=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l78s_0WRnL7hthbRZPmmLSKSCKsxM2DI9FXyAQ=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "000604fc7c7c3c1c"
youtube_img_hash = "000604fc7c7c3c1c"

["猫又おかゆ"]
channel = "UCvaTdHTWBGv3MKj3KVqJVCw"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLT_TLZsRHyNXj_3v1QIfF5Z1LOEIKQPL_7HGH29=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l79MqKq01ItJYUYJ1i5lp0AL0AEnnTTNh62aug=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "efffb38180bdd9c1"
youtube_img_hash = "efffb38180bdd9c1"

["戌神ころね"]
channel = "UChAnqc_AY5_I3Px5dig3X1Q"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLSegxVNNn4QGDwO-jO89ZDcYLSyPUQS3a4KU6QPCw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/ytc/AKedOLSegxVNNn4QGDwO-jO89ZDcYLSyPUQS3a4KU6QPCw=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "c381a9bc38b99bff"
youtube_img_hash = "c381a9bc38b99bff"

["不知火フレア"]
channel = "UCvInZx9h3jC2JzsIzoOebWg"
youtube_url = "https://yt3.ggpht.com/d9aIrGtZR0eI4k1Wnev5f_R4llIBsWnQOjkdsqkMycoAxA3g_zz-jyeBl8tEHfbm1iTg0SJj=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/d9aIrGtZR0eI4k1Wnev5f_R4llIBsWnQOjkdsqkMycoAxA3g_zz-jyeBl8tEHfbm1iTg0SJj=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "5c3e7ee9f8fcc486"
youtube_img_hash = "5c3e7ee9f8fcc486"

["白銀ノエル"]
channel = "UCdyqAaZDKHXg4Ahi7VENThQ"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLS1MTrG3Gn7-Vf_rVNAZ2Ou8KrmUGUXO6TmkLxe=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7_JlV2irL6SKbyQWEuyWXU0UnMQqFP87bxzTg=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "e3d9fd1c18c2e2f1"
youtube_img_hash = "e3d9fd1c18c2e2f1"

["宝鐘マリン"]
channel = "UCCzUftO8KOVkV4wQG1vkUvg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLRFcdtwPHqI4573geBEyNL5h93BxtH5cMy_aL4zUw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l7_dX9d8sMDya_L_ApF7pxUSiwtSOId7Bufd-g=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "38bc3c3c3c1c01e1"
youtube_img_hash = "38bc3c3c3c1c01e1"

["兎田ぺこら"]
channel = "UC1DCedRgGHBdm81E1llLhOQ"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLSmHTeNNQp8A4AwsUPKzBa2ubDBWe6RSaG39mAYTw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l783JgU1dmBOzvsmUfnbMLLOD1c0Gvuo7TKiVw=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "efc78f0f206030bb"
youtube_img_hash = "efc78f0f206030bb"

["潤羽るしあ"]
channel = "UCl_gCybOJRIgOXw6Qb4qJzQ"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLR1en3cN55loPrFL1C5K19o5xGhcKkmr0noD4cO=s88-c-k-c0x00ffffff-no-rj"
youtube_img_hash = "ff9f9fbf9d9c1800"

["星街すいせい"]
channel = "UC5CwaMl1eIgY8h02uZw7u8A"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLT7D-JlLZGTq6Y95nLxeXG2B-7WMGpFXZ7Qa4iY5w=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l797EAYufHUsLlwTxj7Vk_WIuQ0rBjEGEtgR6w=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "d1d4fca2183cb9f4"
youtube_img_hash = "d1d4fca2183cb9f4"

["天音かなた"]
channel = "UCZlDXzGoo7d44bwdNObFacg"
youtube_url = "https://yt3.ggpht.com/TlH8nz5O9UYo5JZ_5fo4JfXdT18N0Ck27wWrulni-c1g5bwes0tVmFiSKICzI1SW7itaTkk9GA=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/TlH8nz5O9UYo5JZ_5fo4JfXdT18N0Ck27wWrulni-c1g5bwes0tVmFiSKICzI1SW7itaTkk9GA=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "fde7f9f8f4d95842"
youtube_img_hash = "fde7f9f8f4d95842"

["角巻わため"]
channel = "UCqm3BQLlJfvkTsX_hvm0UmA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLRWpyqOZzCmuSfmKGNo8TD2L_IRUYSw1wyhHXw-=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l78pYNGWXckjVjmMsSz4iPeCzmWB2DHFW3lLdQ=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "dfbdf8fc84e5f9fd"
youtube_img_hash = "dfbdf8fc84e5f9fd"

["常闇トワ"]
channel = "UC1uv2Oq6kNxgATlCiez59hw"
youtube_url = "https://yt3.ggpht.com/meRnxbRUm5yPSwq8Q5QpI5maFApm5QTGQV_LGblQFsoO0yAV4LI-nSZ70GYwMZ_tbfSa_O8MTCU=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/meRnxbRUm5yPSwq8Q5QpI5maFApm5QTGQV_LGblQFsoO0yAV4LI-nSZ70GYwMZ_tbfSa_O8MTCU=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "ff8180809adba7bf"
youtube_img_hash = "ff8180809edbafff"

["姫森ルーナ"]
channel = "UCa9Y57gfeY0Zro_noHRVrnw"
youtube_url = "https://yt3.ggpht.com/O7m_5HMY_O8yxR3Jhn9cEO1fLNL_GifMERExnAmfY7JrdTRsTjNijTcNYTPN97Llj3zGn8Susw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/O7m_5HMY_O8yxR3Jhn9cEO1fLNL_GifMERExnAmfY7JrdTRsTjNijTcNYTPN97Llj3zGn8Susw=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "1f3b09999d188800"
youtube_img_hash = "1f3b01999d1c8800"

["雪花ラミィ"]
channel = "UCFKOVgVbGmX65RxO3EtH3iw"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQDR06gp26jxNNXh88Hhv1o-pNrnlKrYruqUIOx=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AATXAJzN5Oo_0gI5qPUclliWy8EzU9x5z4oIYliAB3bf=s100-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "7672f9787cd8e0e0"
youtube_img_hash = "f772f9787cd8e0e0"

["桃鈴ねね"]
channel = "UCAWSyEs_Io8MtpY3m-zqILA"
youtube_url = "https://yt3.ggpht.com/bMBMxmB1YVDVazU-8KbB6JZqUHn4YzmFiQRWwEUHCeqm5REPW7HHQChC5xE6e36aqqnXgK4a=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/bMBMxmB1YVDVazU-8KbB6JZqUHn4YzmFiQRWwEUHCeqm5REPW7HHQChC5xE6e36aqqnXgK4a=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "7cfd585a7e784266"
youtube_img_hash = "7cfd585a7e78c266"

["獅白ぼたん"]
channel = "UCUKD-uaobj9jiqB-VXt71mA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQXr6MeUpHI0-yNZIAaGXHvBVowhCWMwGx-zXYs=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AATXAJzO_bOBHuKPycvddNd88hozl2OjaNC-uR7lOAXa=s100-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "ffff9981c99981c3"
youtube_img_hash = "ffff9981c99981c3"

["尾丸ポルカ"]
channel = "UCK9V2B22uJYu3N7eR_BT9QA"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLQI_iYxOpfP8bJklQ_VnS4a9jdrwRRlre_JP1Yp=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AATXAJzMPMCRzpyIsPyp8cOdA2FUwkBotqe6Dh0CmKgA=s100-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "3c7cfefefefe1030"
youtube_img_hash = "3c7cfefefebe1030"

["ラプラス・ダークネス"]
channel = "UCENwRMx5Yh42zWpzURebzTw"
youtube_url = "https://yt3.ggpht.com/roGS60A8a_lDbVakIg1JU3u3hbtjHSTilMGHMizuPKh7tuoY2nl46raxuW2f_83IKFGMjL6Z=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/roGS60A8a_lDbVakIg1JU3u3hbtjHSTilMGHMizuPKh7tuoY2nl46raxuW2f_83IKFGMjL6Z=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "236effbf3b3e1c00"
youtube_img_hash = "236effbf3b3e1c00"

["鷹嶺ルイ"]
channel = "UCs9_O1tRPMQTHQ-N_L6FU2g"
youtube_url = "https://yt3.ggpht.com/KO_kRAeAQ4C4M5xJDFOFHZ79ycCRfMxttefXIDFurZE2fsVPnmlHkMdM5zjEsUTH1i97xnxKNw=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/KO_kRAeAQ4C4M5xJDFOFHZ79ycCRfMxttefXIDFurZE2fsVPnmlHkMdM5zjEsUTH1i97xnxKNw=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "e3d1bd9101bd3911"
youtube_img_hash = "e3d1bd9301bd3911"

["博衣こより"]
channel = "UC6eWCld0KwmyHFbAqK3V-Rw"
youtube_url = "https://yt3.ggpht.com/DNC5rGjlwA4Ae7rhpPmkv_QdjJPl8AfpQT9NcXTLvPbbriL-Y0Ni-gYfFH8uoiF6Ay1EP9VnZAk=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/DNC5rGjlwA4Ae7rhpPmkv_QdjJPl8AfpQT9NcXTLvPbbriL-Y0Ni-gYfFH8uoiF6Ay1EP9VnZAk=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "fbe783b18989d1c0"
youtube_img_hash = "fbe783b18989d1c0"

["沙花叉クロヱ"]
channel = "UCIBY1ollUsauvVi4hW4cumw"
youtube_url = "https://yt3.ggpht.com/_xNtPLKQcQxMTnOr4tAcGz0GEeESsi0bQX9mJEP3fx_50a8GUfUyOG1eyLIld2cCz6GvKABwpQ=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/_xNtPLKQcQxMTnOr4tAcGz0GEeESsi0bQX9mJEP3fx_50a8GUfUyOG1eyLIld2cCz6GvKABwpQ=s176-c-k-c0x00ffffff-no-rj"
holodule_img_hash = "0009fcc8b8fc88c0"
youtube_img_hash = "0009fcc8b8fc88c0"

["風真いろは"]
channel = "UC_vMYWcDjmfdpH6r4TTn1MQ"
youtube_url = "https://yt3.ggpht.com/YK_UCAbw_pFBHSOw_LGWI-WCJDdvMP3y9mmODQ1IFEnNVvcf-M3-q22Db5TLWuAbfboMNFTMIg=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://schedule-static.hololive.tv/image/38680fcce2ca.jpg"
holodule_img_hash = "f3c3efc2dce1c1db"
youtube_img_hash = "f3c3ffc2dce1c1db"

["ホロライブ"]
channel = "UCJFZiqLMntJufDCHc6bQixg"
youtube_url = "https://yt3.ggpht.com/ytc/AKedOLTj0OSWM9TvPy4e8v1_o99OtP3Bg7FXthdkgr2bCQ=s88-c-k-c0x00ffffff-no-rj"
holodule_url = "https://yt3.ggpht.com/a/AGF-l78roMKQjt4568VGVjmLkiOJ-25H9BxD_GH6QA=s88-c-k-c0xffffffff-no-rj-mo"
holodule_img_hash = "b9bd93939999c066"
youtube_img_hash = "b9bd93939999c066"
